ALTER TABLE organizations ADD COLUMN IF NOT EXISTS tax_system VARCHAR(100);
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS vat VARCHAR(50);
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS article_prefix VARCHAR(50);
